name: release

on:
  push:
    tags:
    - '*'

jobs:
  release-unix:
    name: Release for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            name: x86_64-macos
          - os: macos-15
            name: aarch64-macos
          - os: ubuntu-latest
            name: x86_64-linux-gnu
    steps:

      - uses: actions/checkout@v4

      - uses: ocaml-dune/setup-dune@v0

      - name: Cache package build artifacts
        id: package-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/dune/toolchains
          key: ${{ matrix.name }}-toolchains-${{ hashFiles('dune.lock') }}

      - name: Build the project
        run: dune build @install --release --only-packages container-image --verbose

      - run: echo OUT_NAME=container-image-${{ github.ref_name }}-${{ matrix.name }} >> $GITHUB_ENV

      - name: Release a tarball of build outputs
        run: |
          mkdir -p "$OUT_NAME"
          cp -rlf _build/install/default/* "$OUT_NAME"
          tar czf "$OUT_NAME.tar.gz" "$OUT_NAME"

      - name: Upload assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.tar.gz"
