name: release

on:
  push:
    tags:
    - '*'

jobs:
  release-unix:
    name: Release for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            name: x86_64-macos
          - os: macos-15
            name: aarch64-macos
          - os: ubuntu-latest
            name: x86_64-linux-gnu
    steps:

      - name: Install Dune
        run: |
          echo $HOME/.local/bin >> $GITHUB_PATH
          curl -fsSL https://github.com/ocaml-dune/dune-bin-install/releases/download/v3/install.sh | sh -s 3.20.2 --install-root $HOME/.local --no-update-shell-config

      - uses: actions/checkout@v4

      - name: Build the project
        run: DUNE_CONFIG__PKG_BUILD_PROGRESS=enabled dune build @install --release --only-packages container-image

      - run: echo OUT_NAME=container-image-${{ github.ref_name }}-${{ matrix.name }} >> $GITHUB_ENV

      - name: Release a tarball of build outputs
        run: |
          mkdir -p "$OUT_NAME"
          cp -rlf _build/install/default/* "$OUT_NAME"
          tar czf "$OUT_NAME.tar.gz" "$OUT_NAME"

      - name: Upload assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.tar.gz"
